name: Windows Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Install dependencies (Optional)
        run: |
          git pull origin
          docker compose down
          docker compose up -d  --build --remove-orphans
          ./bin/deploy_dev.sh

